### ISSUE TITLE
Together better

### ISSUE THREAD

**Issue by kiquenet** [andyedinborough/aenetmail#151]
Suggestions for working together with:

https://higlabo.codeplex.com/documentation

https://mailsystem.codeplex.com/

https://imapx.codeplex.com/

https://github.com/andyedinborough/aenetmail

https://github.com/jstedfast/MailKit

Lumisoft

References:

http://stackoverflow.com/questions/545724/using-c-sharp-net-librarires-to-check-for-imap-messages-from-gmail-servers

http://stackoverflow.com/questions/670183/accessing-imap-in-c-sharp

I'm newbie, but I have seen several open source components-libraries about IMAP. I'm considerer better for community that gurus and experts work together, IMHO. Greetings.

Jeffrey Stedfast says:

higlab: Seems like a pretty awful implementation, so it'd be a complete waste of my time even trying to integrate with their product. I'd be more productive for me to rewrite their library from scratch... so not gonna bother.

mailsystem: Wow, this is pure crap. It uses String.IndexOf('}') to parse literal strings returned by the IMAP server? Really??? Not worth my time.

imapx: Extremely sloppy parsing code, so again, not worth my time.

aenetmail: Another pretty sloppy MIME, POP3, IMAP, and SMTP implementation.

If they want to use MimeKit to replace their shitty MIME parsers, that's great, but I'm not going to get involved in these projects. It'd be time better spent if I just write a mail library on my own... which is what MailKit is all about.

The only piece that MailKit is missing is an ImapClient at this point, and since all of the other libraries you listed have horrendous implementations of everything, it'd be easier to just write an ImapClient for MailKit than it would be to fix any of those other libraries.﻿

http://jeffreystedfast.blogspot.com.es/2013/10/optimization-tips-tricks-used-by.html#gpluscomments

**Comment by jgboggs** [comment]
Hi,

I just came here to ask a similar question (not sure if proper etiquette is to open a new "issue" or not).

I was wondering what the difference between these projects were (aenetmail, MailKit, S22.Imap, MailSystem.NET, etc) and whether maybe it would be a good idea for all of these projects to work together instead of reinventing the wheel over and over again?

I'm trying to make a decision on which one to use. At first glance, it would appear that MailKit might be the way to go (it has 1012 stars) while aenetmail has 269, S22.Imap has 117 and MailSystem.NET has 17, but I've learned the hard way that more popularity doesn't mean "best".

I plan to post this same question on each of these projects with the hope of getting thoughts of the both the developers and the users (have users used the other libraries? how did they compare? why did you choose the one you settled on?)

Any feedback would be hugely helpful in saving me a lot of time and effort!

**Comment by andyedinborough** [comment]
Honestly, use MailKit.  The guy that runs the project is a real pain and I had to block him for incessant trolling, but he is amazingly dedicated to his project.  This project fulfilled a need I had at the time.  All other projects were terrible--awful apis and riddled with bugs.

If I had time and need, I would rewrite this project.  It works for the most part, and it did what I needed it to.  I don't care for mailkits API, but if you need something well supported, use that.

**Comment by jgboggs** [comment]
Thanks for your feedback!
